BasicConfig:
  serve_groups:
  - "883733189"
  - "114514"
  at_self: "[CQ:at,qq=2256837473]"
  post_url: "http://127.0.0.1:3000/"
  message_post_port: ":8082"
  proxy_port: "10809"
  local_data: "/database/local/"
  local_pic: "/database/local/photos/"
  order_helper_data: "\n/like 给主页点赞10次\n/gpt xx 向gpt3.5提问\n/help 打开指令帮助\n/setu xx 以xx为tag寻找色图[留空为随机]\n/setu_rank 转换色图等级\n/pixivlist xxx 查看pixiv榜单"
PluginConfig:
  sese:
    setu_api: "https://api.lolicon.app/setu/v2"
    setu_rank: 1
    setu_num: 1
  pixiv:
    cookie: "
first_visit_datetime_pc=2024-07-10%2020%3A46%3A50; p_ab_id=3; p_ab_id_2=5; p_ab_d_id=1142497887; yuid_b=NDMEaTQ; device_token=9c5723ff9e1e27d9d495486999d917db; c_type=27; privacy_policy_notification=0; a_type=0; b_type=1; login_ever=yes; _im_vid=01J2QYJSY63VW62YZN759PBFF5; _gid=GA1.2.562259486.1720938754; _gcl_au=1.1.1668346561.1720939538; FCNEC=%5B%5B%22AKsRol_bvP7YWafyWJq4I33V-c948xeRHJjLXQAc5-9Z4fXbkuXtoIc9FD9FkMK1fJ4WsHTo_ZL_sR3BbCAdlNiyLoEx58Ps9WQDjejbJ3vide573zEt3Tyl7zNd4saNVSjIulTjzeQpIV_tPQBg9WoTX2Y2vM9FLw%3D%3D%22%5D%5D; __utmv=235335808.|2=login%20ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=36574162=1^9=p_ab_id=3=1^10=p_ab_id_2=5=1^11=lang=zh=1; PHPSESSID=36574162_nxbODr8UPeCJgok5qfdfFPTrZxO8sGWC; _ga_MZ1NL4PHH0=GS1.1.1721025177.1.1.1721026398.0.0.0; privacy_policy_agreement=0; __utmz=235335808.1721030251.5.2.utmcsr=accounts.pixiv.net|utmccn=(referral)|utmcmd=referral|utmcct=/; __bnc_pfpuid__=16vr-LGoUIi1ST4; __utma=235335808.430545222.1720938223.1721147924.1721200409.12; _ga=GA1.2.489878692.1720938223; _ga_75BBYNYN9J=GS1.1.1721200410.14.1.1721200766.0.0.0; __cf_bm=ZsxQ3JHe9q757qlb9P94IcLzYsyTP2mECgAc3GGZw6E-1721272969-1.0.1.1-D9VMYp1Ky2WGtI9AQ3nOokrxlhXWwyZk1kfbuf.lH.bRvgTmh6wPvx_Qy6Md6teLSrgAUkeDvzpi9dUoeJkmghjiLnyfjrgVtrQJnRtIw7M; cf_clearance=iOOSxNzH6XQ0tFUcI7XTd0gZaOcvYdiGjwYl64RTKa8-1721272974-1.0.1.1-NX7PoaTigL2moEMMNLC6UHYZVZpT6XHovx4ppgtuoeFz7T4s8jNNbxx1AsRqKWP9JEtAfFdsagmLO.LXGJURYg"
    host: "www.pixiv.net"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
  gpt:
    gpt_model: "gpt-3.5-turbo"
    gpt_apikey: "sk-P1gxUnJVnOeRIugKQDmJ0HoA9BF47Te9kTp9ORJHkOyKEagy"
    gpt_url: "https://api.chatanywhere.tech/v1/chat/completions"