BasicConfig:
  serve_groups:
  - "883733189"
  - "114514"
  at_self: "[CQ:at,qq=2256837473]"
  post_url: "http://127.0.0.1:3000/"
  message_post_port: ":8082"
  proxy_port: "10809"
  local_data: "/database/local/"
  local_pic: "/database/local/photos/"
  order_helper_data: "\n/like 给主页点赞10次\n/gpt xx 向gpt3.5提问\n/help 打开指令帮助\n/setu xx 以xx为tag寻找色图[留空为随机]\n/setu_rank 转换色图等级\n/pixivlist xxx 查看pixiv榜单"
PluginConfig:
  sese:
    setu_api: "https://api.lolicon.app/setu/v2"
    setu_rank: 1
    setu_num: 1
  pixiv:
    cookie:
    host: "www.pixiv.net"
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
  gpt:
    gpt_model: "gpt-3.5-turbo"
    gpt_apikey:
    gpt_url: "https://api.chatanywhere.tech/v1/chat/completions"